# @package _group_
save_dir: /mnt/hdd/ncut_features/3d/csc
coords_filename: coords.npy
feats_filename: csc_feats.npy
model: ???
data:
  dataset:
    _target_: ncut.ncut_dataset.NcutScannetDataset
    dataset_dir: /mnt/hdd/scannet
    sensordata_glob_pattern: "*.sens"
    mesh_glob_pattern: "*_vh_clean_2.ply"
    voxel_size: 0.02 # 2cm
    content:
      - mesh_original_coords
      - mesh_voxel_coords
      - mesh_colors

  dataloader: # overwrite dataset with ds and collate_fn with the identity function to use this
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    # num_workers: 2
    # persistent_workers: True