general:
  train_mode: true
  task: "instance_segmentation"
  seed: 42
  checkpoint: null
  backbone_checkpoint: null
  freeze_backbone: false # train only last layer
  linear_probing_backbone: false
  train_on_segments: true
  eval_on_segments: true
  filter_out_instances: false
  save_visualizations: false
  visualization_point_size: 20
  decoder_id: -1
  export: false
  export_root_path: /mnt/hdd/eval_output
  use_dbscan: false # we want to use db scan for testing
  ignore_class_threshold: 100
  project_name: ovseg
  workspace: ovseg
  experiment_name: ???
  num_targets: 201 # model output dim is hardcoded to 128, we want to evaluate on scannet200 though
  add_instance: true
  dbscan_eps: 0.95
  dbscan_min_points: 1
  class_agnostic_evaluation: true


  export_threshold: 0.0001

  reps_per_epoch: 1

  on_crops: false

  scores_threshold: 0.0
  iou_threshold: 1.0

  area: 5

  eval_inner_core: -1 # disabled

  topk_per_image: -1

  ignore_mask_idx: []

  max_batch_size: 99999999

  save_dir: saved/${general.experiment_name}
  # time/commit/md5(config)_uuid
  # time/experiment_id/version_uuid
  # experiment_id: 1 # commit[:8], or unique from logger
  # version: 1 # md5[:8] of config

  gpus: 1

defaults:
  - data: indoor
  - data/data_loaders: simple_loader
  - data/datasets: openvocab_scannet200
  - data/collation_functions: voxelize_collate
  - logging: full
  - model: mask3d
  - metrics: miou
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer
  - callbacks: callbacks_instance_segmentation
  - matcher: hungarian_matcher
  - loss: set_criterion
  - ncut: ncut
  - ncut/eval: eval_pseudo_gt
  - ncut/feature_extraction_3d: csc
  - ncut/feature_extraction_3d/model: Res16UNet34C
  - ncut/feature_extraction_2d: lseg

hydra:
  run:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    subdir: ${hydra.job.num}_${hydra.job.id}
