# @package _group_
pretrained_weights: /mnt/hdd/CSC_Weights/train/Res16UNet34D.pth
_target_: models.lseg_res16unet.Res16UNet34D
in_channels: ${data.in_channels}
out_channels: 32 # csc output dim
out_fpn: true
config:
  dialations: [ 1, 1, 1, 1 ]
  conv1_kernel_size: 3
  bn_momentum: 0.02 # probably irrelevant